// Generated by Xata Codegen 0.21.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "security",
    columns: [
      { name: "ticker", type: "string" },
      { name: "gicsSector", type: "string" },
      { name: "countryOfRisk", type: "string" },
      { name: "companyName", type: "string" },
    ],
  },
  {
    name: "esgMapping",
    columns: [
      { name: "component", type: "string" },
      { name: "value", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Security = InferredTypes["security"];
export type SecurityRecord = Security & XataRecord;

export type EsgMapping = InferredTypes["esgMapping"];
export type EsgMappingRecord = EsgMapping & XataRecord;

export type DatabaseSchema = {
  security: SecurityRecord;
  esgMapping: EsgMappingRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://luw71wh9-s-workspace-vg0spi.us-west-2.xata.sh/db/esg",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
